# The service account bound to the pod
apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo-server-yaml
  labels:
    app.kubernetes.io/name: echo-server-yaml
    app.kubernetes.io/instance: echo-server-yaml
