apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    name: {{ .Values.configMap.name }}
  namespace: {{ .Values.general.defaultNamespace }}
data:
  datasources.yml: |-
    apiVersion: 1

    datasources:
      - name: prometheusdata
        type: prometheus
        access: proxy
        orgId: 1
        url: "http://{{ .Values.prometheus.serviceName }}:{{ .Values.prometheus.servicePort }}"
        basicAuth: false
        isDefault: true
        editable: true

  custom.ini: |-
    [server]
      domain = {{ .Values.general.applicationDNS }}
      root_url = %(protocol)s://%(domain)s:%(http_port)s/monitoring/
      serve_from_sub_path = true
