compact: true
directory:
- charts/ethadapter
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- helm
quiet: true
var-file:
- .checkov/ethadapter/values.yaml
output: cli
