{{- $smartContractInfo := ( .Values.config.smartContractInfo | fromJson) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ethadapter.fullname" . }}
  namespace: {{ template "ethadapter.namespace" . }}
  annotations:
    "description": "Configuration of EthAdapter"
  labels:
    {{- include "ethadapter.labels" . | nindent 4 }}
data:
  rpcAddress: {{ .Values.config.rpcAddress }}
  smartContractAddress: {{ $smartContractInfo.address }}
  smartContractAbi: {{ $smartContractInfo.abi | quote }}