{{- if .Values.secretProviderClass.enabled }}
apiVersion: {{ .Values.secretProviderClass.apiVersion }}
kind: SecretProviderClass
metadata:
  name: {{ include "ethadapter.fullname" . }}
  namespace: {{ template "ethadapter.namespace" . }}
spec:
  {{- toYaml .Values.secretProviderClass.spec | nindent 2 }}
{{- end }}
