apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blockchain-explorer.fullname" . }}
  namespace: {{ default .Release.Namespace }}
  annotations:
    "description": "Configuration of Blockchain Explorer"
data:
  config.json: |-
{{ required "quorumconfig must be set" .Values.quorumConfig | indent 4 }}

  .env.production: |-
{{ required "quorumEnvConfig must be set" .Values.quorumEnvConfig | indent 4 }}