apiVersion: v1
kind: ConfigMap
metadata:
  name: explorer-config
  namespace: explorer
  annotations:
    "description": "Configuration of Blockchain Explorer"
data:
  config.json: |-
{{ required "quorumconfig must be set" .Values.quorumConfig | indent 4 }}

  .env.production: |-
{{ required "quorumEnvProduction must be set" .Values.quorumEnvProduction | indent 4 }}