apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backup-restore.fullname" . }}
  namespace: {{ template "backup-restore.namespace" . }}
  annotations:
    "description": "AWS S3 credentials"
  labels:
    {{- include "backup-restore.labels" . | nindent 4 }}
data:
  awsAccessKeyId: {{ include "backup-restore.awsAccessKeyId" . | b64enc | quote }}
  awsSecretKey: {{ include "backup-restore.awsSecretKey" . | b64enc | quote }}
  awsDefaultRegion: {{ include "backup-restore.awsDefaultRegion" . | b64enc | quote }}
type: Opaque

