#
# The Deployment of the iot-adapter application.
# Note:
# 1. As of Feb-23 2022 the build process needs to run on every container startup as some files are added to ephemeral container disk space.
#    Without these files, the wallet application won't startup.
#    That is also the reason why the container cannot be made readonly currently.
# 2. As of Feb-23 2022 the seedBackup file is injected into the container but not to its desired destination
#    as the build process is overwriting it.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "iot-adapter.fullname" . }}
  labels:
    {{- include "iot-adapter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "iot-adapter.selectorLabels" . | nindent 6 }}
{{- with .Values.deploymentStrategy }}
  strategy:
{{ toYaml . | trim | indent 4 }}
{{- end }}
  template:
    metadata:
      # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "iot-adapter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ include "iot-adapter.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: iot-adapter
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: {{ include "iot-adapter.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        command:
          - sh
          - -c
        args:
            #
            # NOT WORKING: As of Feb-23 2022 the build process must run on every startup as
            # it also write files into ephemeral container disk space, e.g. /{{ .Values.apiHubWorkingFolder }}/apihub-root/demiurge-wallet/loader/environment.js
            #
            # echo "=======> Starting server only - do not run build as apps are already built here..."
            # npm run server
            #
            # Additionally mounting seedsBackup not working (Feb-23 2022) as mounted files are readonly
            # and the build process overwrites it even if no changes occur.
            #
          - |
            cd /{{ .Values.apiHubWorkingFolder }}
            echo "=======> Copying seedsBackupOnStartup to seedsBackup ..."
            cp apihub-root/seedsBackupOnStartup apihub-root/seedsBackup
            echo "=======> Starting application in background process ..."
            npm run server &
            server_pid=$!
            echo "=======> Application running in background with PID=$server_pid"
            echo "=======> Sleiot-adapterng for {{ .Values.config.sleepTime }} ..."
            sleep {{ .Values.config.sleepTime }}
            echo "=======> Starting build process ..."
            npm run build-all
            rc=$?
            echo "=======> Build process done - rc=$rc"
            if [ $rc -eq 0 ]
            then
              echo "=======> Build process successful - Writing file that application is ready ..."
              touch /{{ .Values.apiHubWorkingFolder }}/apihub-root/ready
              tail -f /dev/null
            fi
        volumeMounts:
          # As of Feb-2023 we do NOT mount seedsBackup to its desired destination /{{ .Values.apiHubWorkingFolder }}/apihub-root/seedsBackup
          # as the startup build process will write to that even if there are no changes.
          # Thus, we mount it to different location and copy it to desired location where the file is writeable then.
          - name: iot-adapter-config-volume
            mountPath: /{{ .Values.apiHubWorkingFolder }}/apihub-root/external-volume/config/apihub.json
            subPath: apihub.json
            readOnly: true
          - name: iot-adapter-bdns-config-volume
            mountPath: /{{ .Values.apiHubWorkingFolder }}/apihub-root/external-volume/config/bdns.hosts
            subPath: bdns.hosts
            readOnly: true
          - name: iot-adapter-config-volume
            mountPath: /{{ .Values.apiHubWorkingFolder }}/env.json
            subPath: env.json
            readOnly: true
          - name: iot-adapter-domains-volume
            mountPath: /{{ .Values.apiHubWorkingFolder }}/apihub-root/external-volume/config/domains/{{ required "config.domain must be set" .Values.config.domain }}.json
            subPath: {{ required "config.domain must be set" .Values.config.domain }}.json
            readOnly: true
          - name: iot-adapter-domains-volume
            mountPath: /{{ .Values.apiHubWorkingFolder }}/apihub-root/external-volume/config/domains/{{ required "config.subDomain must be set" .Values.config.subDomain }}.json
            subPath: {{ required "config.subDomain must be set" .Values.config.subDomain }}.json
            readOnly: true
          - name: iot-adapter-domains-volume
            mountPath: /{{ .Values.apiHubWorkingFolder }}/apihub-root/external-volume/config/domains/{{ required "config.vaultDomain must be set" .Values.config.vaultDomain }}.json
            subPath: {{ required "config.vaultDomain must be set" .Values.config.vaultDomain }}.json
            readOnly: true
          - name: iot-adapter-domains-volume
            mountPath: /{{ .Values.apiHubWorkingFolder }}/apihub-root/external-volume/config/domains/default.json
            subPath: default.json
            readOnly: true
          - name: iot-adapter-domains-volume
            mountPath: /{{ .Values.apiHubWorkingFolder }}/apihub-root/external-volume/config/domains/eco.json
            subPath: eco.json
            readOnly: true
      restartPolicy: Always
      volumes:
        - name: iot-adapter-config-volume
          configMap:
            name: {{ include "iot-adapter.fullname" . }}-config
        - name: iot-adapter-bdns-config-volume
          configMap:
            name: {{ include "iot-adapter.fullname" . }}-bdns
        - name: iot-adapter-domains-volume
          configMap:
            name: {{ include "iot-adapter.fullname" . }}-domains
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
