# Default values for new-network usecase.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  # -- The number of the deployed Quorum node
  quorum_node_no:
  # -- The name of the company that makes the deployment
  company: ""
  # -- The name of the use case that is being deployed
  network_name: ""
  # -- The Quorum node public ip address
  enode_address: ""
  # -- The Port of the Quorum node public address
  enode_address_port: "30303"
  # -- NAT address, used for firewall configuration
  NAT: "1.2.3.4"

git_shared_configuration:
  # -- shared github repository name eg. PharmaLedger-IMI/epi-shared-configuration
  repository_name: ""
  # -- github read-write token
  read_write_token: ""

git_upload:
  # --  Enable the automatic upload to the use case shared repository of the shareable data
  enabled: true
  # -- The email used by the git in order to upload the data
  email: ""
  # -- The user used by the git in order to upload the data
  user: ""
  # -- The folder name where the repository will be cloned when the upload procedure is initiated in the post-install step
  git_repo_clone_directory: "helm-charts"
  # -- The description associated with the commit into the use case shared repository of the shareable data
  git_commit_description: "added genesis and node information"

shared_repository_conventions:
  # -- The repository base folder name where the shareable data to will be uploaded
  base_shareable_storage_path: "networks"
  # -- The name of the file that contains the genesis file
  genesis_file_name: "genesis.json"
  # -- The name of the file that contains the validator address
  validator_file_name: "validator.address"
  # -- The name of the file that contains the enode
  enode_file_name: "enode"
  # -- The name of the file that contains the Quorum Node real ip address or dns
  enode_address_file_name: "enode.address"
  # -- The name of the file that contains the Quorum Node port
  enode_address_port_file_name: "enode.address.port"
  # -- The name of the file that contains the NAT address
  nat_file_name: "nat"

image:
  # -- The repository of the Quorum container image
  repository: quorumengineering/quorum
  # -- Image Pull Policy
  pullPolicy: Always
  # -- Image tag
  tag: "21.7.1"
  # -- sha256 digest of the image.
  # Do not add the prefix "@sha256:"
  sha: ""

## -- The strategy of the deployment. Defaults to Recreate as a PVC is bound to it.
## See `kubectl explain deployment.spec.strategy` for more and [https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy)
deploymentStrategy:
  type: Recreate

quorum:
  # -- Directory path to where the persistent volume will be mounted to.
  # Also some config file will be mounted there.
  homeDirPath: "/etc/quorum/qdata"
  # -- Directory path to the Quorum Data Dir. Must be beyond 'homeDirPath' in order to store data on the persistent volume.
  dataDirPath: "/etc/quorum/qdata/dd"
  # -- File path to genesis file
  genesisFilePath: "/etc/quorum/genesis/genesis-geth.json"
  # -- Explicitly set network id
  networkId: 10

  miner:
    # -- Number of CPU threads to use for mining
    threads: 1
    # -- Default minimum difference between two consecutive block's timestamps in seconds
    blockPeriod: 3

  log:
    # -- Logging verbosity: 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=detail
    verbosity: 3
    # -- If enabled, emit specially formatted logging checkpoints
    emitcheckpoints: true

  rpc:
    corsDomain: "*"
    # -- The virtual hostnames for the RPC endpoint to listen for.
    # If you want to restrict it, use {name}-rpc,{name}-rpc.{namespace},{name}-rpc.{namespace}.svc.cluster.local
    vHosts: "*"
    # -- The activated APIs at RPC endpoint.
    api: "admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul"

  metrics:
    # -- Enable metrics endpoint which allows monitoring, e.g. via Prometheus
    enabled: true
    # -- Enable expensive metrics collection and reporting.
    expensive: false
    # -- Enable stand-alone metrics HTTP server listening interface.
    addr: "0.0.0.0"
    # -- Metrics HTTP server listening port.
    port: 9545
    # -- Add annotations for Prometheus to discover metrics endpoint.
    prometheusAnnotationsEnabled: true

use_case:
  newNetwork:
    # -- Enable the new-network use case. Can only be used in collaboration with updatePartnerInfo use case
    enabled: true
    plugin_data_common: >-
      {
        "extradata": "0x0",
        "enode": "",
        "nodeAddress": "",
        "genesisAccount": "0x89"
      }
    plugin_data_secrets: >-
      {
        "genesisKeyStoreAccount": "eyJhZGRyZXNzIjoidGVzdGRhdGEiLCJjcnlwdG8iOnsiY2lwaGVyIjoiYWVzLTEyOC1jdHIiLCJjaXBoZXJ0ZXh0IjoidGVzdGRhdGEiLCJjaXBoZXJwYXJhbXMiOnsiaXYiOiJ0ZXN0ZGF0YSJ9LCJtYWMiOiJ0ZXN0ZGF0YSIsImtkZiI6InNjcnlwdCIsImtkZnBhcmFtcyI6eyJka2xlbiI6MzIsIm4iOjI2MjE0NCwiciI6OCwicCI6MSwic2FsdCI6InRlc3RkYXRhIn19LCJpZCI6InRlc3RkYXRhIiwidmVyc2lvbiI6M30=",
        "nodeKey": "47"
      }

  joinNetwork:
    # -- Enable the join-network use case. Can only be used in collaboration with updatePartnerInfo use case
    enabled: false
    plugin_data_common: >-
      {
        "enode": "08",
        "nodeAddress": "0x3",
        "genesis": "{ \"key\": \"value\" }"
      }
    plugin_data_secrets: >-
      {
        "nodeKey": "3b"
      }

  updatePartnersInfo:
    # -- Enable the update-partners-info use case. Can only be used in collaboration with new-network pr join-network use case
    enabled: false
    plugin_data_common: >-
      {
        
      }
    # -- List of company names who act as peers
    peers: []

# -- Enable persistence using Persistent Volume Claims
# See [http://kubernetes.io/docs/user-guide/persistent-volumes/](http://kubernetes.io/docs/user-guide/persistent-volumes/)
persistence:
  # -- Settings for the data PVC.
  data:
    # -- The name of an existing PVC to use instead of creating a new one.
    existingClaim: ""
    # -- Name of the storage class for data PVC.
    # If empty or not set then storage class will not be set - which means that the default storage class will be used.
    storageClassName: ""
    # -- Size of the data PVC volume.
    size: "3Gi"
    # -- Annotations for the data PVC.
    annotations: {}
    # -- Finalizers for data PVC.
    # See [https://kubernetes.io/docs/concepts/storage/persistent-volumes/#storage-object-in-use-protection](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#storage-object-in-use-protection)
    finalizers:
      - kubernetes.io/pvc-protection
    # -- AccessModes for the data PVC.
    # See [https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes)
    accessModes:
      - ReadWriteOnce
    # -- Selector Labels for the data PVC.
    # See [https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector)
    selectorLabels: {}

  # -- Settings for the logs PVC.
  logs:
    # -- The name of an existing PVC to use instead of creating a new one.
    existingClaim: ""
    # -- Name of the storage class for logs PVC.
    # If empty or not set then storage class will not be set - which means that the default storage class will be used.
    storageClassName: ""
    # -- Size of the logs PVC volume.
    size: "1Gi"
    # -- Annotations for the logs PVC.
    annotations: {}
    # -- Finalizers for logs PVC.
    # See [https://kubernetes.io/docs/concepts/storage/persistent-volumes/#storage-object-in-use-protection](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#storage-object-in-use-protection)
    finalizers:
      - kubernetes.io/pvc-protection
    # -- AccessModes for the logs PVC.
    # See [https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes)
    accessModes:
      - ReadWriteOnce
    # -- Selector Labels for the logs PVC.
    # See [https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector)
    selectorLabels: {}

# -- Number of replicas for the quorum-node !! DO NOT CHANGE !!
replicasCount: 1
# -- Override the full name
fullnameOverride: "quorum"
# -- override the name
nameOverride: "quorum"

# -- Secret(s) for pulling an container image from a private registry.
# See [https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)
imagePullSecrets: []

service:
  # -- Custom service labels
  labels:
  # -- Custom service annotations
  annotations:
    # Let Kubernetes In-tree LoadBalancer controller NOT process this resource (but AWS LB controller 2.2 in this case)
    # See https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/nlb/#configuration
# service.beta.kubernetes.io/aws-load-balancer-type: "external"
    # We want the NLB to be Internet-facing (public)
    # See https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/#lb-scheme
    # service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    # A custom name
    # See https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/#load-balancer-name
    # service.beta.kubernetes.io/aws-load-balancer-name: qn-0
    # Forward traffic to EC2 Instance (thus, a nodePort on the instance will be used)
    # See https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/nlb/#instance-mode_1
    # and https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/#nlb-target-type
    # service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    # IPv4 only
    # See https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/#ip-address-type
    # service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
    # Important: Preserve Client (public) IP address of caller on forwarding traffic to target
    # See https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/#target-group-attributes
    # service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=true,deregistration_delay.timeout_seconds=120,deregistration_delay.connection_termination.enabled=true,stickiness.enabled=true,stickiness.type=source_ip
    # Healthcheck setting - must be within [2, 10] - defaults to 3
    # We use the mininum of 2 to add/remove targets faster from target group
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    # service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    # Use a static Elastic IP address - Elastic IP Allocation IDs required!
    # From offical docs: Public Facing lb only. Length/order must match subnets
    # service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-0aaXXXXXXXXXXXXXX
    # We put the NLB into a certain public subnet only - You can provide the subnet ID or the value of the 'Name' tag
    # From offical docs: You must specify at least one subnet in any of the AZs, both subnetID or subnetName(Name tag on subnets) can be used.
    # See: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/service/annotations/#subnets
    # service.beta.kubernetes.io/aws-load-balancer-subnets: eks-ireland-1-vpc-public-eu-west-1b
    # Only set to true if NLBs subnet is in a different availability zone than the zone affinity of the deployment.
    # service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "false"
    # 1. Load Balancer Proxy Protocol does not work for HTTP based workload!
    # 2. We do not need the Load Balancer Proxy Protocol in our use case, therefore we do not enable it
    # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"

    # Do not use. Use spec.loadBalancerSourceRanges instead!
    # service.beta.kubernetes.io/load-balancer-source-ranges: "8.8.8.8/32,8.8.4.4/32"
  spec:
    # -- A list of CIDR ranges which can access the pod(s) for this service. If list is empty, Kubernetes allows traffic from 0.0.0.0/0 to the Node Security Group(s)
    loadBalancerSourceRanges:
    #  - 8.8.8.8/32
    #  - 8.8.4.4/32

# -- Affinity for scheduling a pod.
# See [https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/)
#
# Notes for AWS: We want to schedule the pod in a certain availability zone, here eu-west-1a
# Must be the same zone as the NLB - see service annotation service.beta.kubernetes.io/aws-load-balancer-subnets
# Please note, that your nodes must be labeled accordingly!
# See [https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone)
affinity:
 # nodeAffinity:
  #  requiredDuringSchedulingIgnoredDuringExecution:
  #    nodeSelectorTerms:
  #      - matchExpressions:
  #          - key: topology.kubernetes.io/zone
  #            operator: In
  #            values:
  #              - eu-west-1a

# -- Pod resources
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

# -- Node Selectors in order to assign pods to certain nodes.
# See [https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/)
nodeSelector: {}

# -- Tolerations for scheduling a pod.
# See [https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
tolerations: []

# -- Annotations added to the pod
podAnnotations: {}

# -- Security Context for the pod.
# See [https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod)
podSecurityContext: {}

# -- Security Context for the application container
# See [https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container)
securityContext: {}
