apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storageVolume.volumeName }}
spec:
  storageClassName: {{ .Values.storageVolume.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageVolume.storageSize }}