apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.general.name }}
  labels:
    app: {{ .Values.general.name }}
spec:
  type: {{ .Values.general.serviceType }}
  ports:
    - port: {{ .Values.general.httpPort }}
      targetPort: {{ .Values.general.httpPort }}
  selector:
    app: {{ .Values.general.name }}