{{- $enode := "" }}
{{- $nodeKeyPublic := ""}}
{{- if .Values.use_case.newNetwork.enabled }}
  {{- $generatedPublicJson := ( .Values.use_case.newNetwork.plugin_data_common | fromJson ) }}
  {{- $enode = $generatedPublicJson.enode }}
  {{- $nodeKeyPublic = $generatedPublicJson.nodeKeyPublic }}
{{- else }}
  {{- $generatedPublicJson := ( .Values.use_case.joinNetwork.plugin_data_common | fromJson ) }}
  {{- $enode = $generatedPublicJson.enode }}
  {{- $nodeKeyPublic = $generatedPublicJson.nodeKeyPublic }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quorumnode.permissionedNodes" . }}
  namespace: {{ default .Release.Namespace }}
  labels:
    name: {{ include "quorumnode.permissionedNodes" . }}
data:
  permissioned-nodes.json: |
    [
      "enode://{{ $enode }}@{{ include "quorumNode.fullname" . }}:30303?discport=0"
{{- if .Values.use_case.updatePartnersInfo.enabled }}
  {{- $generatedUpdatePartnersPublicJson := ( .Values.use_case.updatePartnersInfo.plugin_data_common | fromJson ) }}
  {{- $peers := $generatedUpdatePartnersPublicJson.peers }}
  {{- range $peers }}
    {{- $peer := . }}
      {{- printf "," }}
      {{ printf "enode://%s@%s:%s?discport=0" $peer.enode $peer.enodeAddress $peer.enodeAddressPort | quote }}
  {{- end }}
{{- end }}
    ]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quorumnode.IValidatorCfg" . }}
  namespace: {{ default .Release.Namespace }}
  labels:
    name: {{ include "quorumnode.IValidatorCfg" . }}
data:
  istanbul-validator-config.toml: |-
    vanity = "0x00"
    validators = [
      {{ $nodeKeyPublic | quote }}
{{- if .Values.use_case.updatePartnersInfo.enabled }}
  {{- $generatedUpdatePartnersPublicJson := ( .Values.use_case.updatePartnersInfo.plugin_data_common | fromJson ) }}
  {{- $peers := $generatedUpdatePartnersPublicJson.peers }}
  {{- range $peers }}
    {{- $peer := . }}
      {{- printf "," }}
      {{ $peer.nodeKeyPublic | quote }}
  {{- end }}
{{- end }}
    ]

