{{- $enode := "" }}
{{- if .Values.use_case.newNetwork.enabled }}
  {{- $generatedPublicJson := ( .Values.use_case.newNetwork.plugin_data_common | fromJson ) }}
  {{- $enode = $generatedPublicJson.enode }}
{{- else }}
  {{- $generatedPublicJson := ( .Values.use_case.joinNetwork.plugin_data_common | fromJson ) }}
  {{- $enode = $generatedPublicJson.enode }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quorumNode.fullname" . }}
  namespace: {{ default .Release.Namespace }}
  labels:
    {{- include "quorumNode.labels" . | nindent 4 }}

{{- /*
Deployment Spec:
*/}}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      {{- include "quorumNode.selectorLabels" . | nindent 6 }}
  {{- with .Values.deploymentStrategy }}
  strategy: {{ toYaml . | nindent 4 }}
  {{- end }}

  {{- /*
  Pod Template:
  */}}
  template:
    metadata:
      name: {{ include "quorumNode.fullname" . }}
      labels:
        {{- include "quorumNode.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
      annotations:
      {{- if .Values.secretProviderClass.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/secretproviderclass.yaml") . | sha256sum }}
      {{- else }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- end }}
        checksum/scripts: {{ include (print $.Template.BasePath "/configmap-scripts.yaml") . | sha256sum }}
        checksum/settings: {{ include (print $.Template.BasePath "/configmap-settings.yaml") . | sha256sum }}
      {{- if and .Values.quorum.metrics.enabled .Values.quorum.metrics.prometheusAnnotationsEnabled }}
        prometheus.io/scrape: "true"
        prometheus.io/path: "/debug/metrics/prometheus"
        prometheus.io/port: {{ .Values.quorum.metrics.port | quote }}
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ include "quorumNode.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: quorum-genesis-init
          {{- with .Values.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "quorumnode.image" . | quote }}
          command:
            - sh
            - -cx
          args:
            - |
              if [ ! -f {{ .Values.quorum.dataDirPath }}/genesis_created ]; then
                /usr/local/bin/geth --datadir {{ .Values.quorum.dataDirPath }} init {{ .Values.quorum.genesisFilePath }}
                date > {{ .Values.quorum.dataDirPath }}/genesis_created
              fi
          volumeMounts:
            - name: pvc-data
              mountPath: {{ .Values.quorum.homeMountPath }}
              subPath: {{ include "quorumNode.fullname" . }}
            - name: cm-settings
              mountPath: {{ .Values.quorum.genesisFilePath }}
              subPath: genesis-geth.json
              readOnly: true
      containers:
        - name: quorum
          {{- with .Values.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "quorumnode.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          readinessProbe:
            exec:
              command:
                - ls
                - {{ .Values.quorum.dataDirPath }}/geth.ipc
            initialDelaySeconds: 20
            periodSeconds: 3
          command:
            - sh
            - -cx
          args:
            - |
              # TODO: Not needed? JQ seems not to be used anywhere!
              # apk add jq

              ln -sf {{ .Values.quorum.homeMountPath }}/permission-nodes/permissioned-nodes.json {{ .Values.quorum.dataDirPath }}/permissioned-nodes.json
              ln -sf {{ .Values.quorum.homeMountPath }}/permission-nodes/permissioned-nodes.json {{ .Values.quorum.dataDirPath }}/static-nodes.json
              cat {{ .Values.quorum.genesisFilePath }}
              chmod 644 {{ .Values.quorum.dataDirPath }}/keystore/key
              touch {{ .Values.quorum.dataDirPath }}/password.txt

            {{- if not .Values.persistence.logs.enabled }}
              # If logging is disabled, we can start geth with exec to make it the primary process
              exec \
            {{- end }}
              /usr/local/bin/geth \
                --datadir {{ .Values.quorum.dataDirPath }} \
                --nodiscover \
                --permissioned \
                --nat=none \
                --verbosity {{ .Values.quorum.log.verbosity }} \
            {{- if .Values.quorum.log.emitcheckpoints }}
                --emitcheckpoints \
            {{- end }}
                --gcmode archive \
                --istanbul.blockperiod {{ .Values.quorum.miner.blockPeriod }} --mine --miner.threads {{ .Values.quorum.miner.threads }} \
                --syncmode full \
                --networkid {{ .Values.quorum.networkId }} \
            {{- if .Values.quorum.extraArgs }}
{{ .Values.quorum.extraArgs | indent 16 }} \
            {{- end }}
            {{- if .Values.quorum.metrics.enabled }}
                --metrics --metrics.addr {{ .Values.quorum.metrics.addr | quote }} --metrics.port {{ .Values.quorum.metrics.port | quote }} \
            {{- if .Values.quorum.metrics.expensive }}
                --metrics.expensive \
            {{- end }}
            {{- end }}
                --port 30303 \
                --http --http.addr 0.0.0.0 --http.port 8545 --http.api {{ .Values.quorum.rpc.api | quote }} \
                --http.corsdomain {{ .Values.quorum.rpc.corsDomain | quote }} --http.vhosts {{ .Values.quorum.rpc.vHosts | quote }} \
            {{- if not .Values.persistence.logs.enabled }}
                2>&1
            {{- else }}
                2>&1 | tee -a {{ .Values.quorum.logsMountPath }}/quorum.log
            {{- end }}
          ports:
            - containerPort: 8545
            - containerPort: 30303
          {{- if .Values.quorum.metrics.enabled }}
            - containerPort: {{ .Values.quorum.metrics.port }}
          {{- end }}
          env:
            - name: PRIVATE_CONFIG
              value: "ignore"
            - name: THIS_NODE_ID
              value: {{ include "quorumNode.fullname" . }}
            - name: THIS_ENODE
              value: {{ $enode }}
          volumeMounts:
            - name: pvc-data
              mountPath: {{ .Values.quorum.homeMountPath }}
              subPath: {{ include "quorumNode.fullname" . }}
          {{- if .Values.persistence.logs.enabled }}
            - name: pvc-logs
              mountPath: {{ .Values.quorum.logsMountPath }}
              subPath: {{ include "quorumNode.fullname" . }}-logs
          {{- end }}
            - name: secret
              mountPath: {{ .Values.quorum.dataDirPath }}/geth/nodekey
              subPath: nodekey
              readOnly: true
          {{- if .Values.use_case.newNetwork.enabled }}
            - name: secret
              mountPath: {{ .Values.quorum.dataDirPath }}/keystore/key
              subPath: key
              readOnly: true
          {{- end }}
            - name: cm-settings
              mountPath: {{ .Values.quorum.genesisFilePath }}
              subPath: genesis-geth.json
              readOnly: true
            - name: cm-settings
              mountPath: {{ .Values.quorum.dataDirPath }}/geth/enode
              subPath: enode
              readOnly: true
            - name: cm-settings
              mountPath: {{ .Values.quorum.homeMountPath }}/permission-nodes/permissioned-nodes.json
              subPath: permissioned-nodes.json
              readOnly: true
            - name: cm-settings
              mountPath: {{ .Values.quorum.homeMountPath }}/istanbul-validator-config.toml/istanbul-validator-config.toml
              subPath: istanbul-validator-config.toml
              readOnly: true
            - name: cm-scripts
              mountPath: /geth-helpers/geth-attach.sh
              subPath: geth-attach.sh
              readOnly: true
            - name: cm-scripts
              mountPath: /geth-helpers/geth-exec.sh
              subPath: geth-exec.sh
              readOnly: true
            - name: cm-scripts
              mountPath: {{ .Values.quorum.homeMountPath }}/node-management/ibft_propose.sh
              subPath: ibft_propose.sh
              readOnly: true
            - name: cm-scripts
              mountPath: {{ .Values.quorum.homeMountPath }}/node-management/ibft_propose_all.sh
              subPath: ibft_propose_all.sh
              readOnly: true
      volumes:
        - name: pvc-data
          persistentVolumeClaim:
            claimName: {{ include "quorumnode.PvcData" . }}
      {{- if .Values.persistence.logs.enabled }}
        - name: pvc-logs
          persistentVolumeClaim:
            claimName: {{ include "quorumnode.PvcLogs" . }}
      {{- end }}
        - name: secret
      {{- if .Values.secretProviderClass.enabled }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "quorumNode.fullname" . }}
      {{- else }}
          secret:
            secretName: {{ include "quorumNode.fullname" . }}
            defaultMode: 0440  # mount as r
            items:
              - key: nodekey
                path: nodekey
            {{- if .Values.use_case.newNetwork.enabled }}
              - key: key
                path: key
            {{- end }}
      {{- end }}
        - name: cm-settings
          configMap:
            name: {{ include "quorumNode.fullname" . }}-settings
            defaultMode: 0440  # mount as r
            items:
              - key: enode
                path: enode
              - key: permissioned-nodes.json
                path: permissioned-nodes.json
              - key: istanbul-validator-config.toml
                path: istanbul-validator-config.toml
              - key: genesis-geth.json
                path: genesis-geth.json
        - name: cm-scripts
          configMap:
            name: {{ include "quorumnode.configmap.scripts" . }}
            defaultMode: 0550  # mount as rx
            items:
              - key: geth-attach.sh
                path: geth-attach.sh
              - key: geth-exec.sh
                path: geth-exec.sh
              - key: ibft_propose.sh
                path: ibft_propose.sh
              - key: ibft_propose_all.sh
                path: ibft_propose_all.sh
