{{- if and .Values.persistence.logs.enabled (not (.Values.persistence.logs.existingClaim)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "quorumnode.PvcLogs" . }}
  namespace: {{ default .Release.Namespace }}
  labels:
    {{- include "quorumNode.labels" . | nindent 4 }}
  {{- with .Values.persistence.logs.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.persistence.logs.finalizers }}
  finalizers: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.persistence.logs.storageClassName }}
  storageClassName: {{ .Values.persistence.logs.storageClassName | quote }}
  {{- end }}
  accessModes:
    {{- range .Values.persistence.logs.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size | quote }}
  {{- with .Values.persistence.logs.selectorLabels }}
  selector:
    matchLabels: {{ toYaml . | nindent 6 }}
  {{- end }}
  {{- with .Values.persistence.logs.dataSource }}
  dataSource: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
