{{- if not .Values.persistence.data.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "quorumnode.PvcData" . }}
  namespace: {{ default .Release.Namespace }}
  labels:
    {{- include "quorumNode.labels" . | nindent 4 }}
  {{- with .Values.persistence.data.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- with .Values.persistence.data.finalizers }}
  finalizers:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  {{- if .Values.persistence.data.storageClassName }}
  storageClassName: {{ .Values.persistence.data.storageClassName | quote }}
  {{- end }}
  accessModes:
    {{- range .Values.persistence.data.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
  {{- with .Values.persistence.data.selectorLabels }}
  selector:
    matchLabels:
{{ toYaml . | indent 6 }}
  {{- end }}
{{- end }}
