{{- $enode := "" }}
{{- if .Values.use_case.newNetwork.enabled }}
{{- $generatedPublicJson := ( .Values.use_case.newNetwork.plugin_data_common | fromJson ) }}
{{- $enode = $generatedPublicJson.enode }}
{{- else }}
{{- $generatedPublicJson := ( .Values.use_case.joinNetwork.plugin_data_common | fromJson ) }}
{{- $enode = $generatedPublicJson.enode }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quorumNode.fullname" . }}
  namespace: {{ default .Release.Namespace }}
  labels:
    {{- include "quorumNode.labels" . | nindent 4 }}

{{- /*
Deployment Spec:
*/}}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      {{- include "quorumNode.selectorLabels" . | nindent 6 }}
  {{- with .Values.deploymentStrategy }}
  strategy:
    {{ toYaml . | trim | indent 4 }}
  {{- end }}

  {{- /*
  Pod Template:
  */}}
  template:
    metadata:
      name:  {{ include "quorumNode.fullname" . }}
      labels:
        {{- include "quorumNode.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: quorum-genesis-init-container
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          command:
            - sh
            - -cx
          args:
            - |
              if [ ! -f {{ .Values.blockchain.quorum_data_dir }}/genesis_created ]; then
                /usr/local/bin/geth --datadir {{ .Values.blockchain.quorum_data_dir }} init {{ .Values.blockchain.quorum_genesis_location }}
                date > {{ .Values.blockchain.quorum_data_dir }}/genesis_created
              fi
          env:
            - name: QHOME
              value: {{ .Values.blockchain.quorum_home }}
          volumeMounts:
            - name: quorum-persistent-storage
              mountPath: {{ .Values.blockchain.quorum_home }}
              subPath: {{ include "quorumNode.Identifier" . }}
            - name: genesis-config-persistent-storage
              mountPath: {{ .Values.blockchain.quorum_genesis_location }}
              subPath: genesis-geth.json
      containers:
        - name: quorum
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          readinessProbe:
            exec:
              command:
                - ls
                - {{ .Values.blockchain.quorum_data_dir }}/geth.ipc
            initialDelaySeconds: 20
            periodSeconds: 3
          command:
            - sh
            - -cx
          args:
            - |
              # TODO: Not needed? JQ seems not to be used anywhere!
              # apk add jq

              ln -sf $QUORUM_HOME/permission-nodes/permissioned-nodes.json {{ .Values.blockchain.quorum_data_dir }}/permissioned-nodes.json
              ln -sf $QUORUM_HOME/permission-nodes/permissioned-nodes.json {{ .Values.blockchain.quorum_data_dir }}/static-nodes.json
              cat {{ .Values.blockchain.quorum_genesis_location }}
              chmod 644 {{ .Values.blockchain.quorum_data_dir }}/keystore/key
              touch {{ .Values.blockchain.quorum_data_dir }}/password.txt

              NETWORK_ID=10
              /usr/local/bin/geth \
                --datadir {{ .Values.blockchain.quorum_data_dir }} \
                --gcmode archive --istanbul.blockperiod {{ .Values.blockchain.blockperiod }} --syncmode full \
                --mine --miner.threads 1 \
                --permissioned \
                --nodiscover \
                --nat=none \
                --verbosity 3 \
                --networkid $NETWORK_ID \
                --emitcheckpoints \
                --port 30303 \
                --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul \
                --rpccorsdomain="*" --rpcvhosts={{ include "quorumNode.fullname" . }}-rpc \
                  2>&1 | tee -a {{ .Values.blockchain.quorum_home }}/logs/quorum.log;"
          ports:
            - containerPort: 8545  # RPC Port
            - containerPort: 30303 # Node communication
          env:
            - name: PRIVATE_CONFIG
              value: "ignore"
            - name: QUORUM_HOME
              value: {{ .Values.blockchain.quorum_home }}
            - name: QHOME
              value: {{ .Values.blockchain.quorum_home }}
            - name: THIS_NODE_ID
              value: {{ include "quorumNode.Identifier" . }}
            - name: THIS_ENODE
              value: {{ $enode }}
          volumeMounts:
            - name: quorum-persistent-storage
              mountPath: {{ .Values.blockchain.quorum_home }}
              subPath: {{ include "quorumNode.Identifier" . }}
            - name: quorum-persistent-storage-logs
              mountPath: {{ .Values.blockchain.quorum_home }}/logs
              subPath: {{ include "quorumNode.Identifier" . }}-logs
            - name: genesis-config-persistent-storage
              mountPath: {{ .Values.blockchain.quorum_genesis_location }}
              subPath: genesis-geth.json
            - name: quorum-nodekey
              mountPath: {{ .Values.blockchain.quorum_data_dir }}/geth/nodekey
              subPath: nodekey
            {{- if .Values.use_case.newNetwork.enabled }}
            - name: quorum-key-config-persistent-storage
              mountPath: {{ .Values.blockchain.quorum_data_dir }}/keystore/key
              subPath: key
            {{- end }}
            - name: quorum-enode
              mountPath: {{ .Values.blockchain.quorum_data_dir }}/geth/enode
              subPath: enode
            - name: {{ include "quorumnode.PermissionedCfg" . }}
              mountPath: {{ .Values.blockchain.quorum_home }}/permission-nodes
            - name: {{ include "quorumnode.gethHelpers" . }}
              mountPath: /geth-helpers
            - name: {{ include "quorumnode.IValidatorCfg" . }}
              mountPath: {{ .Values.blockchain.quorum_home }}/istanbul-validator-config.toml
            - name: {{ include "quorumnode.NodeManagement" . }}
              mountPath: {{ .Values.blockchain.quorum_home }}/node-management/ibft_propose.sh
              subPath: ibft_propose.sh
            - name: {{ include "quorumnode.NodeManagement" . }}
              mountPath: {{ .Values.blockchain.quorum_home }}/node-management/ibft_propose_all.sh
              subPath: ibft_propose_all.sh
      volumes:
        {{- if .Values.use_case.newNetwork.enabled }}
        - name: quorum-key-config-persistent-storage
          configMap:
            name: {{ include "quorumNode.Identifier" . }}-account-key-config
            items:
              - key: key
                path: key
        {{- end }}
        - name: {{ include "quorumnode.PermissionedCfg" . }}
          configMap:
            name: {{ include "quorumnode.PermissionedCfg" . }}
            items:
              - key: permissioned-nodes.json
                path: permissioned-nodes.json
        - name: genesis-config-persistent-storage
          configMap:
            name: {{ include "quorumNode.Identifier" . }}-genesis-config
            items:
              - key: genesis-geth.json
                path: genesis-geth.json
        - name: quorum-nodekey
          configMap:
            name: {{ include "quorumNode.Identifier" . }}-nodekey-config
            items:
              - key: nodekey
                path: nodekey
        - name: quorum-enode
          configMap:
            name: {{ include "quorumNode.Identifier" . }}-enode-config
            items:
              - key: enode
                path: enode
        - name: {{ include "quorumnode.gethHelpers" . }}
          configMap:
            name: {{ include "quorumnode.gethHelpers" . }}
            items:
              - key: geth-attach.sh
                path: geth-attach.sh
              - key: geth-exec.sh
                path: geth-exec.sh
            defaultMode: 0777
        - name: {{ include "quorumnode.IValidatorCfg" . }}
          configMap:
            name: {{ include "quorumnode.IValidatorCfg" . }}.toml
        - name: {{ include "quorumnode.NodeManagement" . }}
          configMap:
            name: {{ include "quorumnode.NodeManagement" . }}
            items:
              - key: ibft_propose.sh
                path: ibft_propose.sh
              - key: ibft_propose_all.sh
                path: ibft_propose_all.sh
            defaultMode: 0777
        # PVC (configurable) https://kubernetes.io/docs/concepts/storage/persistent-volumes/#claims-as-volumes
        - name: quorum-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "quorumnode.PvcData" . }}
        - name: quorum-persistent-storage-logs
          persistentVolumeClaim:
            claimName: {{ include "quorumnode.PvcLogs" . }}
