{{- if .Values.use_case.newNetwork.enabled }}
# ethereum / geth account keys (keystore)
{{- $generatedPrivateJson := ( .Values.use_case.newNetwork.plugin_data_secrets | fromJson ) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quorumNode.Identifier" . }}-account-key-config
  namespace: {{ default .Release.Namespace }}
  labels:
    name: {{ include "quorumNode.Identifier" . }}-account-key-config
data:
  key: |-


    {{ toJson ($generatedPrivateJson.genesisKeyStoreAccount | b64dec) }}
  {{- end }}
