{{- if .Values.use_case.newNetwork.enabled }}
  {{- $generatedPublicJson := ( .Values.use_case.newNetwork.plugin_data_common | fromJson ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quorumNode.Identifier" . }}-genesis-config
  namespace: {{ default .Release.Namespace }}
  labels:
    name: {{ include "quorumNode.Identifier" . }}-genesis-config
data:
  genesis-geth.json: |-
    {
        "alloc": {
          "{{ $generatedPublicJson.genesisAccount }}": {
             "balance": "1000000000000000000000000000"
          }
        },
      "coinbase": "0x0000000000000000000000000000000000000000",
      "config": {
        "homesteadBlock": 0,
        "byzantiumBlock": 0,
        "constantinopleBlock": 0,
        "petersburgBlock": 0,
        "istanbulBlock": 0,
        "eip150Block": 0,
        "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "eip155Block": 0,
        "eip158Block": 0,
        "maxCodeSizeConfig": [
          {
            "block": 0,
            "size": 32
          }
        ],
        "chainId": 10,
        "isQuorum": true,
        "istanbul": {
          "epoch": 30000,
          "policy": 0
        }
      },
      "difficulty": "0x1",
      "extraData": "{{ $generatedPublicJson.extradata }}",
      "gasLimit": "0xE0000000",
      "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
      "nonce": "0x0",
      "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "timestamp": "0x00"
    }


  {{- else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quorumNode.Identifier" . }}-genesis-config
  namespace: {{ default .Release.Namespace }}
  labels:
    name: {{ include "quorumNode.Identifier" . }}-genesis-config
data:
  genesis-geth.json: |-
    {{- $genesis := ( .Values.use_case.joinNetwork.plugin_data_common | fromJson ) }}
    {{- $genesis.genesis | nindent 6 }}
{{- end }}

