{{- $enode := "" }}
{{- if .Values.use_case.newNetwork.enabled }}
{{- $generatedPublicJson := ( .Values.use_case.newNetwork.plugin_data_common | fromJson ) }}
{{- $enode = $generatedPublicJson.enode }}
{{- else }}
{{- $generatedPublicJson := ( .Values.use_case.joinNetwork.plugin_data_common | fromJson ) }}
{{- $enode = $generatedPublicJson.enode }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quorumNode.fullname" . }}
  namespace: {{ default .Release.Namespace }}
  labels:
    {{- include "quorumNode.labels" . | nindent 4 }}

spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      {{- include "quorumNode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name:  {{ include "quorumNode.fullname" . }}
      labels:
        {{- include "quorumNode.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end}}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: quorum-genesis-init-container
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.quorum_source.registry }}/{{ .Values.quorum_source.image }}:{{ .Values.quorum_source.version }}"
          command: [ "sh" ]
          args:
            - "-cx"
            - "if [ ! -f $QUORUM_DATA_DIR/genesis_created ]; then
              /usr/local/bin/geth --datadir $QUORUM_DATA_DIR init {{ .Values.blockchain.quorum_genesis_location }}/genesis-geth.json;
              date > $QUORUM_DATA_DIR/genesis_created;
           fi;
          "
          env:
            - name: QUORUM_DATA_DIR
              value: {{ .Values.blockchain.quorum_data_dir }}
            - name: QHOME
              value: {{ .Values.blockchain.quorum_home }}
          volumeMounts:
            - name: quorum-persistent-storage
              mountPath:  {{ .Values.blockchain.quorum_home }}
              subPath: {{ include "quorumNode.Identifier" . }}
            - name: genesis-config-persistent-storage
              mountPath: {{ .Values.blockchain.quorum_genesis_location }}/genesis-geth.json
              subPath: genesis-geth.json

      containers:
        - name: quorum
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          image: "{{ .Values.quorum_source.registry }}/{{ .Values.quorum_source.image }}:{{ .Values.quorum_source.version }}"
          readinessProbe:
            exec:
              command:
                - ls
                - $(QHOME)/dd/geth.ipc
            initialDelaySeconds: 20
            periodSeconds: 3
          command: [ "sh" ]
          args:
            - "-cx"
            - "
           apk add jq;

           ln -s $QUORUM_HOME/permission-nodes/permissioned-nodes.json $QUORUM_DATA_DIR/permissioned-nodes.json;
           ln -s $QUORUM_HOME/permission-nodes/permissioned-nodes.json $QUORUM_DATA_DIR/static-nodes.json;

           cat {{ .Values.blockchain.quorum_genesis_location }}/genesis-geth.json;

           chmod 644 $QUORUM_DATA_DIR/keystore/key;

           touch $QUORUM_DATA_DIR/password.txt;
           NETWORK_ID=10
           RPC_APIS=admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum
           args=\" --gcmode archive --istanbul.blockperiod {{ .Values.blockchain.blockperiod }} --syncmode full --mine --miner.threads 1 \";
           RPC_APIS=\"$RPC_APIS,istanbul\";
           /usr/local/bin/geth \
           --datadir $QUORUM_DATA_DIR \
           $args \
           --permissioned \
           --nodiscover \
           --nat=none \
           --verbosity 3 \
           --networkid $NETWORK_ID \
           --emitcheckpoints \
           --port 30303 \
           --rpc \
           --rpcaddr 0.0.0.0 \
           --rpcport 8545 \
           --rpcapi $RPC_APIS \
           --rpccorsdomain=\"*\" \
           --rpcvhosts={{ include "quorumNode.fullname" . }}-rpc \
            2>&1 | tee -a {{ .Values.blockchain.quorum_home }}/logs/quorum.log;"
          ports:
            - containerPort: 8545
            - containerPort: 30303

          env:
            - name: PRIVATE_CONFIG
              value: "ignore"
            - name: QUORUM_DATA_DIR
              value: {{ .Values.blockchain.quorum_data_dir }}
            - name: QUORUM_HOME
              value: {{ .Values.blockchain.quorum_home }}
            - name: QHOME
              value: {{ .Values.blockchain.quorum_home }}
            - name: THIS_NODE_ID
              value: {{ include "quorumNode.Identifier" . }}
            - name: THIS_ENODE
              value: {{ $enode }}
          volumeMounts:
            - name: quorum-persistent-storage
              mountPath: {{ .Values.blockchain.quorum_home }}
              subPath: {{ include "quorumNode.Identifier" . }}
            - name: quorum-persistent-storage-logs
              mountPath: {{ .Values.blockchain.quorum_home }}/logs
              subPath: {{ include "quorumNode.Identifier" . }}-logs
            - name: genesis-config-persistent-storage
              mountPath: {{ .Values.blockchain.quorum_genesis_location }}/genesis-geth.json
              subPath: genesis-geth.json
            - name: quorum-nodekey
              mountPath: {{ .Values.blockchain.quorum_data_dir }}/geth/nodekey
              subPath: nodekey
{{- if .Values.use_case.newNetwork.enabled }}
            - name: quorum-key-config-persistent-storage
              mountPath: {{ .Values.blockchain.quorum_data_dir }}/keystore/key
              subPath: key
{{- end }}
            - name: quorum-enode
              mountPath: {{ .Values.blockchain.quorum_data_dir }}/geth/enode
              subPath: enode
            - name: {{ include "quorumnode.PermissionedCfg" . }}
              mountPath: {{ .Values.blockchain.quorum_home }}/permission-nodes
            - name: {{ include "quorumnode.gethHelpers" . }}
              mountPath: /geth-helpers
            - name: {{ include "quorumnode.IValidatorCfg" . }}
              mountPath: {{ .Values.blockchain.quorum_home }}/istanbul-validator-config.toml
            - name: {{ include "quorumnode.NodeManagement" . }}
              mountPath: {{ .Values.blockchain.quorum_home }}/node-management/ibft_propose.sh
              subPath: ibft_propose.sh
            - name: {{ include "quorumnode.NodeManagement" . }}
              mountPath: {{ .Values.blockchain.quorum_home }}/node-management/ibft_propose_all.sh
              subPath: ibft_propose_all.sh
      volumes:
{{- if .Values.use_case.newNetwork.enabled }}
        - name: quorum-key-config-persistent-storage
          configMap:
            name: {{ include "quorumNode.Identifier" . }}-account-key-config
            items:
              - key: key
                path: key
{{- end }}
        - name: {{ include "quorumnode.PermissionedCfg" . }}
          configMap:
            name: {{ include "quorumnode.PermissionedCfg" . }}
            items:
              - key: permissioned-nodes.json
                path: permissioned-nodes.json
        - name: genesis-config-persistent-storage
          configMap:
            name: {{ include "quorumNode.Identifier" . }}-genesis-config
            items:
              - key: genesis-geth.json
                path: genesis-geth.json
        - name: quorum-nodekey
          configMap:
            name: {{ include "quorumNode.Identifier" . }}-nodekey-config
            items:
              - key: nodekey
                path: nodekey
        - name: quorum-enode
          configMap:
            name: {{ include "quorumNode.Identifier" . }}-enode-config
            items:
              - key: enode
                path: enode
        - name: {{ include "quorumnode.gethHelpers" . }}
          configMap:
            name: {{ include "quorumnode.gethHelpers" . }}
            items:
              - key: geth-attach.sh
                path: geth-attach.sh
              - key: geth-exec.sh
                path: geth-exec.sh
            defaultMode: 0777
        - name: {{ include "quorumnode.IValidatorCfg" . }}
          configMap:
            name: {{ include "quorumnode.IValidatorCfg" . }}.toml
        - name: {{ include "quorumnode.NodeManagement" . }}
          configMap:
            name: {{ include "quorumnode.NodeManagement" . }}
            items:
              - key: ibft_propose.sh
                path: ibft_propose.sh
              - key: ibft_propose_all.sh
                path: ibft_propose_all.sh
            defaultMode: 0777
        # PVC (configurable) https://kubernetes.io/docs/concepts/storage/persistent-volumes/#claims-as-volumes
        - name: quorum-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "quorumnode.PvcData" . }}
        - name: quorum-persistent-storage-logs
          persistentVolumeClaim:
            claimName: {{ include "quorumnode.PvcLogs" . }}
