{{- $enode := "" }}
{{- $nodeKeyPublic := ""}}
{{- if .Values.use_case.newNetwork.enabled }}
  {{- $generatedPublicJson := ( .Values.use_case.newNetwork.plugin_data_common | fromJson ) }}
  {{- $enode = $generatedPublicJson.enode }}
  {{- $nodeKeyPublic = $generatedPublicJson.nodeKeyPublic }}
{{- else }}
  {{- $generatedPublicJson := ( .Values.use_case.joinNetwork.plugin_data_common | fromJson ) }}
  {{- $enode = $generatedPublicJson.enode }}
  {{- $nodeKeyPublic = $generatedPublicJson.nodeKeyPublic }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quorumnode.PermissionedCfg" . }}
  namespace: {{ default .Release.Namespace }}
  labels:
    name: {{ include "quorumnode.PermissionedCfg" . }}
data:
  permissioned-nodes.json: |
    [
      "enode://{{ $enode }}@{{ include "quorumNode.fullname" . }}:30303?discport=0"
{{- if .Values.use_case.updatePartnersInfo.enabled }}
  {{- $generatedUpdatePartnersPublicJson := ( .Values.use_case.updatePartnersInfo.plugin_data_common | fromJson ) }}
  {{- $peers := $generatedUpdatePartnersPublicJson.peers }}
  {{- range $peers }}
    {{- $peer := . }}
      {{- printf "," }}
      {{ printf "enode://%s@%s:%s?discport=0" $peer.enode $peer.enodeAddress $peer.enodeAddressPort | quote }}
  {{- end }}
{{- end }}
    ]

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quorumnode.NodeManagement" . }}
  namespace: {{ default .Release.Namespace }}
  labels:
    name: {{ include "quorumnode.NodeManagement" . }}
data:
  ibft_propose.sh: |-
    #/bin/ash

    if [ $# -lt 1 ]; then
      echo " An address to vote in, or out, must be provided: "
      echo " ./propose_ibft.sh HEX_ADDRESS (true|false)"
    fi

    ADDRESS=$1
    VOTE_BOOL=true

    if [ $# -eq 2 ]; then
     VOTE_BOOL=$2
    fi
    RES=$(geth --exec "istanbul.propose(\"$1\", $VOTE_BOOL)" attach ipc:{{ .Values.quorum.dataDirPath }}/geth.ipc)
    echo $RES
  ibft_propose_all.sh: |-
    #!/bin/ash
    #set -xe

    for Addr in $( awk '/validators/,0' {{ .Values.quorum.homeDirPath }}/istanbul-validator-config.toml/istanbul-validator-config.toml | grep "0x" | sed 's/,//g; s/"//g' ); do
      echo $Addr
      {{ .Values.quorum.homeDirPath }}/node-management/ibft_propose.sh $Addr true
    done
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quorumnode.IValidatorCfg" . }}.toml
  namespace: {{ default .Release.Namespace }}
  labels:
    name: {{ include "quorumnode.IValidatorCfg" . }}
data:
  istanbul-validator-config.toml: |-
    vanity = "0x00"
    validators = [
      {{ $nodeKeyPublic | quote }}
{{- if .Values.use_case.updatePartnersInfo.enabled }}
  {{- $generatedUpdatePartnersPublicJson := ( .Values.use_case.updatePartnersInfo.plugin_data_common | fromJson ) }}
  {{- $peers := $generatedUpdatePartnersPublicJson.peers }}
  {{- range $peers }}
    {{- $peer := . }}
      {{- printf "," }}
      {{ $peer.nodeKeyPublic | quote }}
  {{- end }}
{{- end }}
    ]

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quorumnode.gethHelpers" . }}
  namespace: {{ default .Release.Namespace }}
  labels:
    name: {{ include "quorumnode.gethHelpers" . }}
data:
  geth-attach.sh: |-
    #!/bin/sh

    # helper for connecting to geth from
    # outside the container
    # kubectl exec -it $POD -c quorum -- /geth-helpers/geth-attach.sh
    echo "connecting to geth {{ .Values.quorum.homeDirPath }}"
    geth attach --datadir {{ .Values.quorum.dataDirPath }} {{ .Values.quorum.dataDirPath }}/geth.ipc
  geth-exec.sh: |-
    #!/bin/sh

    # helper for connecting to geth from
    # outside the container
    # kubectl exec -it $POD -c quorum -- /geth-helpers/geth-exec.sh "admin.peers.length"

    GETH_CMD="eth.blockNumber"
    if [ "$#" -gt 0 ]; then
      GETH_CMD=$1
    fi
    # see: https://github.com/ethereum/go-ethereum/pull/17281
    # https://github.com/ethereum/go-ethereum/issues/16905
    # to avoid warning being returned
    # "WARN [02-20|00:21:04.382] Sanitizing cache to Go's GC limits  provided=1024 updated=663"
    geth --exec $GETH_CMD  --cache=16 attach --datadir {{ .Values.quorum.dataDirPath }} {{ .Values.quorum.dataDirPath }}/geth.ipc
