{{- if not .Values.secretProviderClass.enabled }}
{{- $nodeKey := "" }}
{{- if .Values.use_case.newNetwork.enabled }}
  {{- $nodeKey = ( .Values.use_case.newNetwork.plugin_data_secrets | fromJson ).nodeKey }}
{{- else }}
  {{- $nodeKey = ( .Values.use_case.joinNetwork.plugin_data_secrets | fromJson ).nodeKey }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quorumNode.fullname" . }}
  namespace: {{ default .Release.Namespace }}
  labels:
    name: {{ include "quorumNode.fullname" . }}
data:
  nodekey: | {{ $nodeKey | b64enc | nindent 4 }}
{{- if .Values.use_case.newNetwork.enabled }}
{{- $genesisKeyStoreAccount := ( .Values.use_case.newNetwork.plugin_data_secrets | fromJson ).genesisKeyStoreAccount }}
  {{- /*
    Note: $genesisKeyStoreAccount is already base64 encoded
  */}}
  key: |- {{ $genesisKeyStoreAccount | nindent 4 }}
{{- end }}
type: Opaque
{{- end }}
