{{- if .Values.secretProviderClass.enabled }}
apiVersion: {{ .Values.secretProviderClass.apiVersion }}
kind: SecretProviderClass
metadata:
  name: {{ include "quorumNode.fullname" . }}
  namespace: {{ default .Release.Namespace }}
spec:
  {{- toYaml .Values.secretProviderClass.spec | nindent 2 }}
{{- end }}
