{{- $nodeKey := "" }}
{{- if .Values.use_case.newNetwork.enabled }}
  {{- $nodeKey = ( .Values.use_case.newNetwork.plugin_data_secrets | fromJson ).nodeKey }}
{{- else }}
  {{- $nodeKey = ( .Values.use_case.joinNetwork.plugin_data_secrets | fromJson ).nodeKey }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quorumNode.fullname" . }}-nodekey
  namespace: {{ default .Release.Namespace }}
  labels:
    name: {{ include "quorumNode.fullname" . }}-nodekey
data:
  nodekey: | {{ $nodeKey | b64enc | nindent 4 }}
type: Opaque