{{- if .Values.service.p2p.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quorumNode.fullname" . }}-p2p
  namespace: {{ default .Release.Namespace }}
  labels: {{ include "quorumNode.labels" . | nindent 4 }}
  {{- with .Values.service.p2p.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
spec:
{{- if eq .Values.service.p2p.type "LoadBalancer" }}
  {{- if .Values.service.p2p.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.p2p.loadBalancerIP }}
  {{- end }}
  {{- with .Values.service.p2p.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
  selector:
    {{- include "quorumNode.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.p2p.type }}
  ports:
    - name: p2p-listener
      protocol: TCP
      port: {{ .Values.service.p2p.port }}
      targetPort: 30303
{{- end }}
