{{- if .Values.service.rpc.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quorumNode.fullname" . }}-rpc
  namespace: {{ default .Release.Namespace }}
  labels: {{ include "quorumNode.labels" . | nindent 4 }}
  {{- with .Values.service.rpc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
spec:
{{- if eq .Values.service.rpc.type "LoadBalancer" }}
  {{- if .Values.service.rpc.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.rpc.loadBalancerIP }}
  {{- end }}
  {{- with .Values.service.rpc.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
  selector:
    {{- include "quorumNode.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.rpc.type }}
  ports:
    - name: rpc-listener
      protocol: TCP
      port: {{ .Values.service.rpc.port }}
      targetPort: 8545
{{- end }}
