apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "quorum-node-metrics-exporter.fullname" . }}
  namespace: {{ template "quorum-node-metrics-exporter.namespace" . }}
  labels:
    {{- include "quorum-node-metrics-exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "quorum-node-metrics-exporter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "quorum-node-metrics-exporter.serviceAccountName" . }}
