apiVersion: v1
kind: Service
metadata:
  name: {{ include "quorum-node-metrics-exporter.fullname" . }}
  namespace: {{ template "quorum-node-metrics-exporter.namespace" . }}
  labels:
    {{- include "quorum-node-metrics-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP | quote }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "quorum-node-metrics-exporter.selectorLabels" . | nindent 4 }}
