{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quorum-node-metrics-exporter.serviceAccountName" . }}
  namespace: {{ template "quorum-node-metrics-exporter.namespace" . }}
  labels:
    {{- include "quorum-node-metrics-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
