{
 "title": "Quorum Node Flow Logs",
 "description": "Analyzes AWS VPC Flow Logs to gain insights into the traffic from/to Quorum Node",
 "tags": [
  "quorum",
  "traffic",
  "ingress",
  "egress",
  "peers"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "OUTGOING traffic (egress)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Outgoing accepted traffic from NAT-GW to internet at port 30303",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expression": "filter action=\"ACCEPT\"\n| filter dstPort=30303\n| filter not isIpv4InSubnet(dstAddr, \"TODO: Replace with the CIDR range of your VPC, e.g. 10.0.0.0/16\") # filter by external addresses; we do not want to count healthchecks from NLB to node\n  # Filter source by public subnets where NAT-GW sits (as node->NAT is counted as own connection, we filter these)\n| filter (isIpv4InSubnet(srcAddr, \"TODO: Replace with the CIDR range of your first public subnet, e.g. 10.0.0.0/22\") or isIpv4InSubnet(srcAddr, \"TODO: Replace with the CIDR range of your second public subnet, e.g. 10.0.4.0/22\") or isIpv4InSubnet(srcAddr, \"TODO: Replace with the CIDR range of your third public subnet, e.g. 10.0.8.0/22\"))\n| stats count(*) as count, sum(bytes) by dstAddr as address\n| sort count desc\n| limit 40",
     "logGroupNames": [
      "TODO: replace with you CloudWatch Log Group name"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "external",
      "addresses"
     ]
    }
   ]
  },
  {
   "title": "Outgoing REJECTED traffic from NAT-GW to internet at port 30303",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expression": "filter action=\"REJECT\"\n| filter dstPort=30303\n| filter not isIpv4InSubnet(dstAddr, \"TODO: Replace with the CIDR range of your VPC, e.g. 10.0.0.0/16\") # filter by external addresses; we do not want to count healthchecks from NLB to node\n  # Filter source by public subnets where NAT-GW sits (as node->NAT is counted as own connection, we filter these)\n| filter (isIpv4InSubnet(srcAddr, \"TODO: Replace with the CIDR range of your first public subnet, e.g. 10.0.0.0/22\") or isIpv4InSubnet(srcAddr, \"TODO: Replace with the CIDR range of your second public subnet, e.g. 10.0.4.0/22\") or isIpv4InSubnet(srcAddr, \"TODO: Replace with the CIDR range of your third public subnet, e.g. 10.0.8.0/22\"))\n| stats count(*) as count, sum(bytes) by dstAddr as address\n| sort count desc\n| limit 40",
     "logGroupNames": [
      "TODO: replace with you CloudWatch Log Group name"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "external",
      "addresses"
     ]
    }
   ]
  },
  { "title": "INCOMING traffic (ingress)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Incoming accepted traffic from internet to our node at port 30303",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expression": "filter action=\"ACCEPT\"\n| filter dstPort=30303 # Filter by Quorum Port\n| filter not isIpv4InSubnet(srcAddr, \"TODO: Replace with the CIDR range of your VPC, e.g. 10.0.0.0/16\") # filter by external addresses\n  # filter destination by private subnets (as external IP->NLB is counted as own connection, we want filter these):\n| filter (isIpv4InSubnet(dstAddr, \"TODO: Replace with the CIDR range of your first private subnet, e.g. 10.0.16.0/20\") or isIpv4InSubnet(dstAddr, \"TODO: Replace with the CIDR range of your second private subnet, e.g. 10.0.32.0/20\") or isIpv4InSubnet(dstAddr, \"TODO: Replace with the CIDR range of your third private subnet, e.g. 10.0.48.0/20\"))\n| stats count(*) as count, sum(bytes) by srcAddr as address\n| sort count desc\n| limit 40",
     "logGroupNames": [
      "TODO: replace with you CloudWatch Log Group name"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "Quorum",
      "Port"
     ]
    }
   ]
  },
  {
   "title": "Incoming REJECTED traffic from internet to our node at port 30303",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expression": "filter action=\"REJECT\"\n| filter dstPort=30303 # Filter by Quorum Port\n| filter not isIpv4InSubnet(srcAddr, \"TODO: Replace with the CIDR range of your VPC, e.g. 10.0.0.0/16\") # filter by external addresses\n  # filter destination by private subnets (as external IP->NLB is counted as own connection, we want filter these):\n| filter (isIpv4InSubnet(dstAddr, \"TODO: Replace with the CIDR range of your first private subnet, e.g. 10.0.16.0/20\") or isIpv4InSubnet(dstAddr, \"TODO: Replace with the CIDR range of your second private subnet, e.g. 10.0.32.0/20\") or isIpv4InSubnet(dstAddr, \"TODO: Replace with the CIDR range of your third private subnet, e.g. 10.0.48.0/20\"))\n| stats count(*) as count, sum(bytes) by srcAddr as address\n| sort count desc\n| limit 40",
     "logGroupNames": [
      "TODO: replace with you CloudWatch Log Group name"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "Quorum",
      "Port"
     ]
    }
   ]
  }
 ]
}