general:
  name: grafana
  httpPort: 3000
  defaultNamespace: default
  # The DNS of the application (e.g. csc.nvs.pharmaledger.app)
  applicationDNS: ""

deployment:
  replicaSet: 1
  imageName: grafana/grafana:latest
  imagePullPolicy: IfNotPresent

configMap:
  name: grafana-configuration
  volumeName: grafana-config-volume
  datasources:
    mountPath: /etc/grafana/provisioning/datasources/datasources.yml
    subPath: datasources.yml
  customServer:
    mountPath: /etc/grafana/custom.ini
    subPath: custom.ini

storageVolume:
  volumeName: grafana-storage-volume
  mountPath: /var/lib/grafana
  # If empty or not set then storage class will not be set - which means that the default storage class will be used.
  storageClassName: ""
  storageSize: 5Gi

prometheus:
  serviceName: prometheus
  servicePort: 9090
