apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smartcontract.configMapNameAnchoringInfo" . }}
  annotations:
    "description": "abi (string), address (string), info (JSON)"
  labels:
    {{- include "smartcontract.labels" . | nindent 4 }}
data:
{{ include "smartcontract.anchoringSmartContractData" . | indent 2}}
