{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "smartcontract.serviceAccountName" . }}
  namespace: {{ template "smartcontract.namespace" . }}
  labels:
    {{- include "smartcontract.labels" . | nindent 4 }}
  annotations:
    "description": "ServiceAccount for SmartContract deployment"
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
