#
# The Deployment of the epi application.
# Note:
# 1. As of Feb-23 2022 the build process needs to run on every container startup as some files are added to ephemeral container disk space.
#    Without these files, the wallet application won't startup.
#    That is also the reason why the container cannot be made readonly currently.
# 2. As of Feb-23 2022 the seedBackup file is injected into the container but not to its desired destination 
#    as the build process is overwriting it.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "epi.fullname" . }}
  labels:
    {{- include "epi.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "epi.selectorLabels" . | nindent 6 }}
{{- with .Values.deploymentStrategy }}
  strategy:
{{ toYaml . | trim | indent 4 }}
{{- end }}
  template:
    metadata:
      # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "epi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ include "epi.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: epi
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: {{ include "epi.runner.image" . | quote }}
        imagePullPolicy: {{ .Values.runner.image.pullPolicy | default "Always" }}
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        command:
          - sh
          - -c
        args:
          - |
            echo "=======> Starting server only - do not run build as apps are already built here..."
            npm run server
        volumeMounts:
          - name: epi-external-volume
            mountPath: /ePI-workspace/apihub-root/external-volume
          - name: epi-secret-volume
            mountPath: /ePI-workspace/apihub-root/external-volume/config/apihub.json
            subPath: apihub.json
            readOnly: true
          - name: epi-bdns-config-volume
            mountPath: /ePI-workspace/apihub-root/external-volume/config/bdns.hosts
            subPath: bdns.hosts
            readOnly: true
          - name: epi-secret-volume
            mountPath: /ePI-workspace/env.json
            subPath: env.json
            readOnly: true
          - name: epi-domains-volume
            mountPath: /ePI-workspace/apihub-root/external-volume/config/domains/{{ required "config.domain must be set" .Values.config.domain }}.json
            subPath: {{ required "config.domain must be set" .Values.config.domain }}.json
            readOnly: true
          - name: epi-domains-volume
            mountPath: /ePI-workspace/apihub-root/external-volume/config/domains/{{ required "config.subDomain must be set" .Values.config.subDomain }}.json
            subPath: {{ required "config.subDomain must be set" .Values.config.subDomain }}.json
            readOnly: true
          - name: epi-domains-volume
            mountPath: /ePI-workspace/apihub-root/external-volume/config/domains/{{ required "config.vaultDomain must be set" .Values.config.vaultDomain }}.json
            subPath: {{ required "config.vaultDomain must be set" .Values.config.vaultDomain }}.json
            readOnly: true
            #
            # Mounts for environment configs to trust-loader
            #
          - name: epi-env-volume
            mountPath: /ePI-workspace/trust-loader-config/demiurge-wallet/loader/environment.js
            subPath: demiurge-environment.js
            readOnly: true
          - name: epi-env-volume
            mountPath: /ePI-workspace/trust-loader-config/dsu-explorer/loader/environment.js
            subPath: dsu-explorer-environment.js
            readOnly: true
          - name: epi-env-volume
            mountPath: /ePI-workspace/trust-loader-config/dsu-fabric-wallet/loader/environment.js
            subPath: dsu-fabric-environment.js
            readOnly: true
          - name: epi-env-volume
            mountPath: /ePI-workspace/trust-loader-config/leaflet-wallet/loader/environment.js
            subPath: leaflet-environment.js
            readOnly: true
            #
            # Mounts for environment configs to wallets itself
            #
          - name: epi-env-volume
            mountPath: /ePI-workspace/apihub-root/demiurge-wallet/loader/environment.js
            subPath: demiurge-environment.js
            readOnly: true
          - name: epi-env-volume
            mountPath: /ePI-workspace/apihub-root/dsu-explorer/loader/environment.js
            subPath: dsu-explorer-environment.js
            readOnly: true
          - name: epi-env-volume
            mountPath: /ePI-workspace/apihub-root/dsu-fabric-wallet/loader/environment.js
            subPath: dsu-fabric-environment.js
            readOnly: true
          - name: epi-env-volume
            mountPath: /ePI-workspace/apihub-root/leaflet-wallet/loader/environment.js
            subPath: leaflet-environment.js
            readOnly: true

          # # 
          # # TODO: Remove with v1.3.1 - https://github.com/PharmaLedger-IMI/epi-workspace/tree/master/apihub-root/external-volume/wallets
          # #
          # - name: epi-env-volume
          #   mountPath: /ePI-workspace/apihub-root/external-volume/wallets/leaflet-wallet/wallet-patch/environment.json
          #   subPath: leaflet-wallet_wallet-patch_environment.json
          #   readOnly: true
          # - name: epi-env-volume
          #   mountPath: /ePI-workspace/apihub-root/external-volume/wallets/leaflet-wallet/wallet-patch/security.policies
          #   subPath: leaflet-wallet_wallet-patch_security.policies
          #   readOnly: true
          # - name: epi-env-volume
          #   mountPath: /ePI-workspace/apihub-root/external-volume/wallets/demiurge-wallet/wallet-patch/messages/createEnclave.json
          #   subPath: demiurge-wallet_wallet-patch_messages_createEnclave.json
          #   readOnly: true
          # - name: epi-env-volume
          #   mountPath: /ePI-workspace/apihub-root/external-volume/wallets/demiurge-wallet/wallet-patch/messages/createGroup.json
          #   subPath: demiurge-wallet_wallet-patch_messages_createGroup.json
          #   readOnly: true

      restartPolicy: Always
      volumes:
        - name: epi-secret-volume
        {{- if .Values.secretProviderClass.enabled }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "epi.fullname" . }}
        {{- else }}
          secret:
            secretName: {{ include "epi.fullname" . }}
            defaultMode: 0400
        {{- end }}

        # - name: epi-config-volume
        #   configMap:
        #     name: {{ include "epi.fullname" . }}-config
        - name: epi-bdns-config-volume
          configMap:
            name: {{ include "epi.fullname" . }}-bdns
        - name: epi-domains-volume
          configMap:
            name: {{ include "epi.fullname" . }}-domains
        - name: epi-env-volume
          configMap:
            name: {{ include "epi.fullname" . }}-environment
        - name: epi-external-volume
          persistentVolumeClaim:
            claimName:  {{ include "epi.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
