{{- /*
ServiceAccount will be created on pre-install (or on pre-upgrade if you activate ServiceAccount) and will remain for the whole lifetime of the helm installation!
It will be deleted by job Cleanup.
*/}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "epi.serviceAccountName" . }}
  namespace: {{ template "epi.namespace" . }}
  labels:
    {{- include "epi.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-1"
    {{- /*
    Skip deleting this resource when a helm operation (such as helm uninstall, helm upgrade or helm rollback) would result in its deletion.
    */}}
    "helm.sh/resource-policy": keep
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
