compact: true
directory:
- charts/epi
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- helm
quiet: true
skip-check:
- CKV_K8S_21 # do not use default namespace
soft-fail: true
var-file:
- .checkov/epi/values.yaml
output: cli
