compact: true
directory:
- charts/epi
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- helm
quiet: true
skip-check:
- CKV_K8S_21
- CKV_K8S_15
- CKV_K8S_38 # CKV_K8S_38: "Ensure that Service Account Tokens are only mounted where necessary"
soft-fail: true
var-file:
- .checkov/epi/values.yaml
output: cli
