config:
  buildSecretKey: "nosecretfordevelopers"  # pragma: allowlist secret
  bdnsHosts: "somebdns"

# Set namespace via values
namespaceOverride: "epi"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 5m
    memory: 128Mi

# Set seccompProfile as this is not set by default
kubectl:
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

runner:
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

builder:
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
