config:
  buildSecretKey: "nosecretfordevelopers"  # pragma: allowlist secret
  bdnsHosts: "somebdns"

# Set namespace via values
namespaceOverride: "epi"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 5m
    memory: 128Mi

