name: Validate code
on: [push, pull_request]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Run Pre-Commit and linter
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
        name: Checkout

      # https://github.com/marketplace/actions/engineerd-configurator
      - uses: engineerd/configurator@479197cb150e720c848c8dfbe12da101471258e3 # v0.0.8
        name: Setup helm
        with:
          name: helm
          url: https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz
          pathInArchive: linux-amd64/helm
      - run: helm version

      # https://github.com/marketplace/actions/engineerd-configurator
      - uses: engineerd/configurator@479197cb150e720c848c8dfbe12da101471258e3 # v0.0.8
        name: Setup helm-docs
        with:
          name: helm-docs
          url: https://github.com/norwoodj/helm-docs/releases/download/v1.5.0/helm-docs_1.5.0_Linux_x86_64.tar.gz
          pathInArchive: helm-docs
      - run: helm-docs --version

      - name: Helm Lint
        run: helm lint ./charts/* --strict

      - uses: pre-commit/action@9b88afc9cd57fd75b655d5c71bd38146d07135fe # v2.0.3
        name: Run pre-commit

  checkov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
        name: Checkout

      # https://github.com/bridgecrewio/checkov-action/tree/v12.1469.0
      - uses: bridgecrewio/checkov-action@85bd3080490ce5978dce5f754a993c42b1ef1d2b # v12.1469.0
        name: Checkov ethadapter
        with:
          config_file: .checkov/ethadapter/.checkov.yaml
          # we need to override these values as they will always set by the github action
          directory: 'charts/ethadapter' # we need to set this value! - see https://github.com/bridgecrewio/checkov-action/issues/77
          output_format: 'cli' # override default value 'sarif'  - https://github.com/bridgecrewio/checkov-action/blob/v12.1469.0/action.yml#L37

      # https://github.com/bridgecrewio/checkov-action/tree/v12.1469.0
      - uses: bridgecrewio/checkov-action@85bd3080490ce5978dce5f754a993c42b1ef1d2b # v12.1469.0
        name: Checkov epi
        with:
          config_file: .checkov/epi/.checkov.yaml
          # we need to override these values as they will always set by the github action
          directory: 'charts/epi' # we need to set this value! - see https://github.com/bridgecrewio/checkov-action/issues/77
          output_format: 'cli' # override default value 'sarif'  - https://github.com/bridgecrewio/checkov-action/blob/v12.1469.0/action.yml#L37
